### ISSUE TITLE
Unhandled rejection error using Node 9

### ISSUE THREAD

**Issue by alvinmeimoun** [snowyu/promise-sequence.js#3]
Hi,

I'm starting using this library, and when i run it i see the following warnings
`(node:1932) UnhandledPromiseRejectionWarning: TypeError: task.apply is not a function
    at ******/node_modules/promise-sequence/lib/sequence.js:28:65
(node:1932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I don't know when the mentionned future will be effective but it will broke this library

This issue already appear with Node 8 but with less details

**Comment by snowyu** [comment]
1. `task.apply is not a function` which means some task is not promise function. eg, 

```js
sequence([promose1, null])
```

maybe I should return this directly when it is not function?

2.  `UnhandledPromiseRejectionWarning` you can add all promises to catch  the error, or just ignore this.

```js
function ignoreError(err) {}
sequence([promose1.catch(ignoreError), promose2.catch(ignoreError)]).then(...)
```
